CREATE TABLE IF NOT EXISTS slack_events (
    id              SERIAL PRIMARY KEY,
    event_id        VARCHAR(100) UNIQUE NOT NULL,
    event_type      VARCHAR(50),
    event_subtype   VARCHAR(50),
    team_id         VARCHAR(50),
    channel_id      VARCHAR(50),
    user_id         VARCHAR(50),
    text            TEXT,
    ts              VARCHAR(30),
    thread_ts       VARCHAR(30),
    event_time      BIGINT,
    file_1_id       VARCHAR(50),
    file_1_name     VARCHAR(255),
    file_1_mimetype VARCHAR(100),
    file_1_url      TEXT,
    file_2_id       VARCHAR(50),
    file_2_name     VARCHAR(255),
    file_2_mimetype VARCHAR(100),
    file_2_url      TEXT,
    file_3_id       VARCHAR(50),
    file_3_name     VARCHAR(255),
    file_3_mimetype VARCHAR(100),
    file_3_url      TEXT,
    file_4_id       VARCHAR(50),
    file_4_name     VARCHAR(255),
    file_4_mimetype VARCHAR(100),
    file_4_url      TEXT,
    file_5_id       VARCHAR(50),
    file_5_name     VARCHAR(255),
    file_5_mimetype VARCHAR(100),
    file_5_url      TEXT,
    raw_payload     JSONB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed       BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_slack_events_thread_ts ON slack_events(thread_ts);
CREATE INDEX IF NOT EXISTS idx_slack_events_processed ON slack_events(processed);